### ISSUE TITLE
Client secrets are exposed (!)

### ISSUE THREAD

**Issue by joepb** [lurumad/swagger-ui-pkce#1]
Hey @lurumad ,

Using `options.OAuthUsePkce();` indeed makes the authentication use PKCE correctly.

However, by also using the line `options.OAuthClientSecret(...);` you are _still_ putting the secret visible in your swagger frontend. This makes it very easy to people to get hold of your secret and potentially abuse it.

https://github.com/lurumad/swagger-ui-pkce/blob/9886f3cb36081b6b6981c303e9c9d237217920f4/SwashbucklePkce/Startup.cs#L58

I've tested the code without that line and PKCE authentication works perfectly fine, without having my secret key visible in the frontend.

Could you please look into this issue and put a remark in your blog https://lurumad.github.io/swagger-ui-with-pkce-using-swashbuckle-asp-net-core ?
(By the way a great blog post. Without that one I would have never figured out how to do the PKCE in SwaggerUI!) 

Joep

**Comment by joepb** [comment]
Documented here: https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/

> 🚨 Never use this parameter in your production environment. It exposes cruicial security information. This feature is intended for dev/test environments only. 🚨

**Comment by lurumad** [comment]
Hi @joepb 

I will change it asap!

Regards!

**Comment by dennisroche** [comment]
Otherwise great example/blog post, but this needs to be fixed. It is a common error that I've seen across samples that I've been looking at today.

**Comment by lurumad** [comment]
It should be fixed!

Cheers!
